import { getElementOrThrow } from './utils'
import { Config } from './types'

// Basic
const DEFAULT_CONTAINER = getElementOrThrow('snowfall')
const DEFAULT_BACKGROUND = '#0d0014'
const DEFAULT_PRIMARY_COLOR = '#8d90b7'
const DEFAULT_SECONDARY_COLOR = '#ffffff'
const DEFAULT_DENSITY = 200
const DEFAULT_FADE_IN = true

// Wave
const DEFAULT_AMPLITUDE = 1.0
const DEFAULT_FREQUENCY = 0.02
export const DEFAULT_WAVE = {
  frequency: DEFAULT_FREQUENCY,
  amplitude: DEFAULT_AMPLITUDE
}

// Gravity
const DEFAULT_GRAVITY_ANGLE = 90
const DEFAULT_GRAVITY_STRENGTH = 0.7
const DEFAULT_RESPECT_ORIENTATION = false
export const DEFAULT_GRAVITY = {
  angle: DEFAULT_GRAVITY_ANGLE,
  strength: DEFAULT_GRAVITY_STRENGTH,
  respectOrientation: DEFAULT_RESPECT_ORIENTATION
}

// Wind
const DEFAULT_WIND_ANGLE = 0
const DEFAULT_WIND_STRENGTH = 0
const DEFAULT_WIND_GUSTS = true
const DEFAULT_WIND_IN_ADDITIONAL_STRENGTH_MIN = 1
const DEFAULT_WIND_IN_ADDITIONAL_STRENGTH_MAX = 3
const DEFAULT_WIND_IN_ADDITIONAL_STRENGTH = {
  min: DEFAULT_WIND_IN_ADDITIONAL_STRENGTH_MAX,
  max: DEFAULT_WIND_IN_ADDITIONAL_STRENGTH_MIN
}
const DEFAULT_WIND_IN_DURATION_MIN = 1000
const DEFAULT_WIND_IN_DURATION_MAX = 3000
const DEFAULT_WIND_IN_DURATION = {
  min: DEFAULT_WIND_IN_DURATION_MIN,
  max: DEFAULT_WIND_IN_DURATION_MAX
}
const DEFAULT_WIND_IN_DELAY_MIN = 1000
const DEFAULT_WIND_IN_DELAY_MAX = 10000
const DEFAULT_WIND_IN_DELAY = {
  min: DEFAULT_WIND_IN_DELAY_MIN,
  max: DEFAULT_WIND_IN_DELAY_MAX
}
const DEFAULT_WIND_OUT_DELAY_MIN = 5000
const DEFAULT_WIND_OUT_DELAY_MAX = 10000
const DEFAULT_WIND_OUT_DELAY = {
  min: DEFAULT_WIND_OUT_DELAY_MIN,
  max: DEFAULT_WIND_OUT_DELAY_MAX
}
const DEFAULT_WIND_OUT_DURATION_MAX = 10000
const DEFAULT_WIND_OUT_DURATION_MIN = 1000
const DEFAULT_WIND_OUT_DURATION = {
  min: DEFAULT_WIND_OUT_DURATION_MIN,
  max: DEFAULT_WIND_OUT_DURATION_MAX
}
const DEFAULT_WIND_OUT_CHANGE_CHANCE = 0.25
const DEFAULT_WIND_OUT = {
  duration: DEFAULT_WIND_OUT_DURATION,
  delay: DEFAULT_WIND_OUT_DELAY,
  changeChance: DEFAULT_WIND_OUT_CHANGE_CHANCE
}
const DEFAULT_WIND_IN = {
  additionalStrength: DEFAULT_WIND_IN_ADDITIONAL_STRENGTH,
  duration: DEFAULT_WIND_IN_DURATION,
  delay: DEFAULT_WIND_IN_DELAY
}
export const DEFAULT_WIND = {
  angle: DEFAULT_WIND_ANGLE,
  strength: DEFAULT_WIND_STRENGTH,
  gusts: DEFAULT_WIND_GUSTS,
  in: DEFAULT_WIND_IN,
  out: DEFAULT_WIND_OUT
}

// Config
export const DEFAULT_CONFIG: Config = {
  attachTo: DEFAULT_CONTAINER,
  background: DEFAULT_BACKGROUND,
  primary: DEFAULT_PRIMARY_COLOR,
  secondary: DEFAULT_SECONDARY_COLOR,
  density: DEFAULT_DENSITY,
  fadeIn: DEFAULT_FADE_IN,
  wave: DEFAULT_WAVE,
  gravity: DEFAULT_GRAVITY,
  wind: DEFAULT_WIND
}
