import { getElementOrThrow } from './utils'
import { BaseConfig, Config, ConfigLayer, UserConfig } from './types'

// Basic
export const DEFAULT_CONTAINER_ID = 'snowfall'
export const DEFAULT_CONTAINER = getElementOrThrow(DEFAULT_CONTAINER_ID)
export const DEFAULT_BACKGROUND = '#0d0014'
export const DEFAULT_PRIMARY_COLOR = '#8d90b7'
export const DEFAULT_SECONDARY_COLOR = '#ffffff'
export const DEFAULT_DENSITY = 200
export const DEFAULT_FADE_IN = true

// Wave
export const DEFAULT_AMPLITUDE = 1.0
export const DEFAULT_FREQUENCY = 0.02
export const DEFAULT_WAVE = {
  frequency: DEFAULT_FREQUENCY,
  amplitude: DEFAULT_AMPLITUDE
}

// Gravity
export const DEFAULT_GRAVITY_ANGLE = 90
export const DEFAULT_GRAVITY_STRENGTH = 0.7
export const DEFAULT_RESPECT_ORIENTATION = false
export const DEFAULT_GRAVITY = {
  angle: DEFAULT_GRAVITY_ANGLE,
  strength: DEFAULT_GRAVITY_STRENGTH,
  respectOrientation: DEFAULT_RESPECT_ORIENTATION
}

// Wind
export const DEFAULT_WIND_ANGLE = 0
export const DEFAULT_WIND_STRENGTH = 0
export const DEFAULT_WIND_GUSTS = true
export const DEFAULT_WIND_IN_ADDITIONAL_STRENGTH_MIN = 1
export const DEFAULT_WIND_IN_ADDITIONAL_STRENGTH_MAX = 3
export const DEFAULT_WIND_IN_ADDITIONAL_STRENGTH = {
  min: DEFAULT_WIND_IN_ADDITIONAL_STRENGTH_MIN,
  max: DEFAULT_WIND_IN_ADDITIONAL_STRENGTH_MAX
}
export const DEFAULT_WIND_IN_DURATION_MIN = 1000
export const DEFAULT_WIND_IN_DURATION_MAX = 3000
export const DEFAULT_WIND_IN_DURATION = {
  min: DEFAULT_WIND_IN_DURATION_MIN,
  max: DEFAULT_WIND_IN_DURATION_MAX
}
export const DEFAULT_WIND_IN_DELAY_MIN = 1000
export const DEFAULT_WIND_IN_DELAY_MAX = 10000
export const DEFAULT_WIND_IN_DELAY = {
  min: DEFAULT_WIND_IN_DELAY_MIN,
  max: DEFAULT_WIND_IN_DELAY_MAX
}
export const DEFAULT_WIND_OUT_DELAY_MIN = 5000
export const DEFAULT_WIND_OUT_DELAY_MAX = 10000
export const DEFAULT_WIND_OUT_DELAY = {
  min: DEFAULT_WIND_OUT_DELAY_MIN,
  max: DEFAULT_WIND_OUT_DELAY_MAX
}
export const DEFAULT_WIND_OUT_DURATION_MAX = 10000
export const DEFAULT_WIND_OUT_DURATION_MIN = 1000
export const DEFAULT_WIND_OUT_DURATION = {
  min: DEFAULT_WIND_OUT_DURATION_MIN,
  max: DEFAULT_WIND_OUT_DURATION_MAX
}
export const DEFAULT_WIND_OUT_CHANGE_CHANCE = 0.25
export const DEFAULT_WIND_OUT = {
  duration: DEFAULT_WIND_OUT_DURATION,
  delay: DEFAULT_WIND_OUT_DELAY,
  changeChance: DEFAULT_WIND_OUT_CHANGE_CHANCE
}
export const DEFAULT_WIND_IN = {
  additionalStrength: DEFAULT_WIND_IN_ADDITIONAL_STRENGTH,
  duration: DEFAULT_WIND_IN_DURATION,
  delay: DEFAULT_WIND_IN_DELAY
}
export const DEFAULT_WIND = {
  angle: DEFAULT_WIND_ANGLE,
  strength: DEFAULT_WIND_STRENGTH,
  gusts: DEFAULT_WIND_GUSTS,
  in: DEFAULT_WIND_IN,
  out: DEFAULT_WIND_OUT
}

export const DEFAULT_LAYER: ConfigLayer = {
  colour: DEFAULT_PRIMARY_COLOR,
  density: DEFAULT_DENSITY,
  fadeIn: DEFAULT_FADE_IN,
  wave: DEFAULT_WAVE,
  gravity: DEFAULT_GRAVITY,
  wind: DEFAULT_WIND
}

export const DEFAULT_LAYERS: ConfigLayer[] = [
  { ...DEFAULT_LAYER, colour: DEFAULT_PRIMARY_COLOR },
  { ...DEFAULT_LAYER, colour: DEFAULT_SECONDARY_COLOR }
]

export const DEFAULT_BASE_CONFIG: BaseConfig = {
  // attachTo: DEFAULT_CONTAINER,
  background: DEFAULT_BACKGROUND,
  density: DEFAULT_DENSITY,
  fadeIn: DEFAULT_FADE_IN,
  wave: DEFAULT_WAVE,
  gravity: DEFAULT_GRAVITY,
  wind: DEFAULT_WIND,
  layers: DEFAULT_LAYERS,
  colour: DEFAULT_PRIMARY_COLOR
}

// Config
export const DEFAULT_CONFIG: Config = {
  ...DEFAULT_BASE_CONFIG,
  attachTo: DEFAULT_CONTAINER
}

export const DEFAULT_USER_CONFIG: UserConfig = {
  ...DEFAULT_BASE_CONFIG,
  attachTo: DEFAULT_CONTAINER_ID
}
